= How night shift affects patient safety ?

== Participant 1
No, there is no harm in the safety of the patient, but it is the patients due to which the mind remains engaged in the work, if an emergency comes or the patient's condition deteriorates, then automatically we become alert and attentive, and how the night We don't even know it passes.

== Participant 2
Yes it can, and for this we should be alert and responsible, because in our profession the night shift is necessary for the patients and we should understand this.

== Participant 3
no, not at all, everyone stays very serious about patient safety always.

== Participant 4
no no, patient safety can't be disturbed. that is the 1st priority in work. 

== Participant 5
yes all these minor mistakes can create big issues for patient.

== Participant 6
no, night shift won't affect patient's safety.

== Participant 7
no not at all.

== Participant 8
patient safety can't be hampered because of night shift, everyone stays serious about their patients.

== Participant 9
no patient safety is the 1st priority, and everyone takes it seriously.

== Participant 10
for patients we are here to care about, and there won't be any disturbances in that. if i feel sick i ask other staffs to assist my patient and i take a break but i never had let any negligence regarding patient safety.

== Participant 11
in safety of patient it can't affect.

== Participant 12
patient's safety can be affected from many ways like if someone could not stay awake or be attentive during night shift because of any reason, that can be very dangerous for a patient's life.

== Participant 13
we become more careful when there is chance of deterioration in patient's condition, so i don't think night shift have to do anything with patient safety.

== Participant 14
night shift is just a shift, it can't affect safety of patient.

== Participant 15
i don't think night shift have anything to do with the patient safety.

== Participant 16
if we won't be attentive the patient safety may get hampered with errors in our work.

== Participant 17
it can affect for sure if we won't pay attention.

== Participant 18
night shift won't affect patient safety, we work very carefully in all shifts.

== Participant 19
patients safety is all dependent on the nurses, if nurses are not well skilled and prepared for night shift its possible to have error in patient safety.

== Participant 20
there is so much self control needed to perform night shift. the patient is here depended on us, we always have to keep our personal health issues out of reach to out patients. patient safety is most important to be attentive about during night shift as no one will be there even to notice and inform if there is anything wrong with patient.