= What is the best pattern of sleep for night shifts ?

== Participant 1
There is no such thing as the best pattern of sleep, as I do not feel as relaxed by sleeping during the day as much as I do with sleep at night. All I can say is that a gap should be given in the middle of the night shifts.

== Participant 2
For people like me, i would say better than trying to maintain a sleeping pattern, meditating a little when you can't sleep will probably give you some relaxation, because you know that sleep is not complete.

== Participant 3
Actually we should get 8 hours of sleep. Which is not possible in the sharing room.

== Participant 4
According to me, after returning from duty in the morning, one should prepare more food and sleep after eating a little and should sleep comfortably till 4-5 pm. in the evening, one can heat the morning meal, eat and should leave for duty.

== Participant 5
we should complete atleast 7-8 hours sleep, sometimes we still not feel active because at night works like writing handover again writing critical chart, these things are little boring stuffs which makes me even more lazy, giving medicine and giving rounds with doctors those works are interesting and we can't get distracted. 

== Participant 6
yes, i have delayed periods and that was because of incomplete rest and sleep.

== Participant 7
completing 6 hours of sleep will help, it helps for me.

== Participant 8
oo

== Participant 9
the problem is i don't feel sleepy during day, i can't maintain and complete my sleep.

== Participant 10
we should complete 8 hours of sleep before coming for night shift.

== Participant 11
if i sleep at 1st half of the day just after leaving the shift, then only i'm able to complete my sleep. and i think we all need to complete atleast 8 hours of sleep before going for night shift.

== Participant 12
best sleeping pattern would be i think to complete 6-8 hours of sleep, for me 4-5 hours is enough as i don't get sleep during day.

== Participant 13
we should complete 8 hours of sleep, so that we can stay attentive atleast for half of the shift, then on we have to be involved in some activities otherwise we'll feel sleepy.

== Participant 14
actually it depends on my work which i can do during day when i have night shift, such as going to market for grocery and all. so i manage to sleep for 4-5 hours.

== Participant 15
4-5 hour of sleep is enough for me to complete my sleep.  

== Participant 16
in 2nd half if i complete 6-7 hours of sleep, then its good for me to work in night shift.

== Participant 17
on the 1st night i don't need any preparation, even if i try i won't get sleep. on the 2nd day after returning from night shift i directly go to bed and sleep atleast for 6-7 hours and that helps for me.

== Participant 18
after night shift if i'm returning to room directly going to sleep and sleep till evening then i feel refreshed and i can work peacefully at night.

== Participant 19
if i sleep for 5-6 hours during afternoon till evening, it helps me to stay fresh till late night.

== Participant 20
actually we should sleep at least for 5 to 6 hours before coming for work, but its really not possible for me, in my roommates also got night shift in same day by chance then its good that we all can sleep quite but when shifts are different they'll woke up when i'll return from my duty and they'll keep making noise coz they'll cook, do phone calls and i can't complaint because its same for them also when they have night shift.