= Does night shift affect your hormones, if yes, how?

== Participant 1
NO, haven't felt any such hormonal issue yet.

== Participant 2
Hormones means there is a problem in digestion, I get disturbance in daily bowel movements.

== Participant 3
no, i never felt any hormonal issues yet.

== Participant 4
no, i never felt any hormonal problem in such.

== Participant 5
Speaking of hormonal disturbances, there is a problem in digestion, I get acidity a lot. I can't drink water during night shift, can't remember at night and the whole i'll be sleeping.

== Participant 6
ha

== Participant 7
hormonal in such, digestion problem and acidity i suffer from sometimes.

== Participant 8
no, i don't think.

== Participant 9
i feel dehydrated and also indigestion.

== Participant 10
no, i never felt as such. 

== Participant 11
hormonal in such i would say only digestive issues i have faced yet.

== Participant 12
not to me, but many of friends are having problem in their periods, mostly delay and irregular. many are loosing weight and some are gaining as well. 

== Participant 13
no, i never had such experiences.

== Participant 14
yes, i have hormonal issue we'll have because we can't drink enough water and the lack in sleep is always there.

== Participant 15
no, i got habituated.

== Participant 16
yes, the digestion issue i face the most.

== Participant 17
i have experienced hormonal disturbances resulting in my digestion and in my mood.

== Participant 18
no, i never faced any hormonal issues.

== Participant 19
no, i never faced any hormonal issues.

== Participant 20
yes, 1st major disturbance is digestion, because of eating in odd times and i have acidity and many other problems.