= How night shift affects your social life ?

== Participant 1
I am not married, I live with friends in hostel, the friends I have also have the same status as me, so no one can complain for time or participation. There is no such special effect. Until someone complains or blame, its effect is not known.

== Participant 2
Social life means, people who live with me here in my room sometimes get irritated due to night shift. Like if I had a night shift and I want to sleep during the day but my roommates do not have a night, they will cook or do something and because of that I will not be able to sleep but I cannot blame them because when their night shift When it happens, they also feel the same way, and no one does it intentionally.

== Participant 3
no no, nothing to social life.

== Participant 4
no, not much, If I am sleeping after coming from night shift and my roommate has evening shift and he is cooking food by playing song, I can't tell him anything because everyone has same situation, no one can enjoy because of shifts . That's why everyone has to adjust a little.

== Participant 5
There is also disturbance in social life, I am not able to get involved in plans with friends. As it was Christmas gathering today, juniors had invited but could not go due to duty. and there are plans which i had to cancel just to sleep after a night shift.

== Participant 6
i am a kind of person who don't like to go out much, so i never had such issues.

== Participant 7
it affects, like we can plan anything together not even an outing with friends as everyone will have different shifts, we have to cancel many things because of changing shifts or we'll have to plan without some of our friends that's painful because we are the only family here for each other.

== Participant 8
we can't get actively involved in any events or programs with friends as everyone have different shifts.

== Participant 9
yes, i always miss birthdays and outings with friends because of shifts. in our profession we can't ask for leave together.

== Participant 10
in entire week we get an off day that's the night off, we get it after 2 nights and its literally useless we only can sleep on that day. so social life like enjoying with friends or going out for even a movie is not possible. we plan on some holiday off to take a leave and request our in-charge to grant us leave on same day its rarely possible to get that. so, night shift indirectly disturbs our social life so much.

== Participant 11
yes, in participating with friends is difficult with shift work.

== Participant 12
yes, once during durga pooja we had planned to go out with friends it was on my night off day and i came already late by 9:30 am and i was so tired because i had a really critical patient that night and i couldn't even sat whole night, that i had to cancel that plan and i just slept and also my friends got upset and went without me.

== Participant 13
no, i keep the duty in 1st priority, so there is no such disturbance. social life will bw there but career is the 1st thing to think about.

== Participant 14
 we are Bengalis and we have most of the family events during night, and every week there will be night shift so i miss many of the events.

 == Participant 15
 little bit, because the only off day i get is after night shift so i have to choose whether i want to socialize or sleep. its one or the other type of optional situation where mostly i choose to sleep.

 == Participant 16
 yes, social life means with friends if we want to plan for an outing we can't because of different shifts everyone has.

 == Participant 17
 the invitation for events won't come according to my shift right, so i also have this issues in maintaining social relations here, because i can't attend many such events because when ever i get a little i run for visiting my family because i miss my mom.

 == Participant 18
 not seriously, its manageable.

 == Participant 19
 yes we always had to cancel or miss the plans because events will most probably during night and we can't avoid the shift. i'll share the just going to happen incident with you, tomorrow there is one sister's birthday party and i have night shift and i'm going to miss that.

 == Participant 20
 in social life there is not much difficulties, as i don't have much friends but i have some friends and i miss many planned events because my shift doesn't match with them. its last week only my friends went for movie and then shopping when i was staying room to complete my sleep as i had my 2nd night shift that evening.