= What is the impact of night shifts in your daily life ? Do night shifts shorten your life ?

== Participant 1
Because the duration of time is so long, 12 hours, I get very tired and I feel sleepy and disturbed. Daily routine gets disturbed, I don't like night shift because of these issues. Yes, it seems like a short day, after going from duty, I am falling straight on the bed. it's noon when i wake up and then i'm having breakfast. It is not that I am doing duty only during working hours, here I am on duty even after my shift.

== Participant 2
I do not have sleep during the day, and because of this reason, even after waking up all night, I am not able to complete my sleep during the day. Due to exhaustion, I am not able to do any other work also. Because after going from duty I have to sleep on the next day, so that day seems short because I used to sleep for half the time.

== Participant 3
Nothing much, I get a little headache and I find it a problem to cook food after coming from night.

== Participant 4
yes, I don't know how the day ends.

== Participant 5
life becomes something which i can't explain to you, where the days goes during night shifts i can't sense, at night we are on duty during day i'm sleeping, there is day and night just for name.

== Participant 6
yeah it definitely feels like the day is being shorter because we have to manage food and also have to sleep.

== Participant 7
all day goes only in sleeping. it obviously shorten the life.

== Participant 8
yes, all 3 days during and after night shifts goes only in sleeping, and it shortens our life.

== Participant 9
yes it shortens our life because it goes on sleeping.

== Participant 10
night shift takes a lot of time, because we have to complete our sleep.

== Participant 11
yes the days after night shifts are very short, i go back from shift and sleep for whole day and the day ends. it makes life short.

== Participant 12
yes, the day after night shift is invisible because it goes only in sleeping and doing other works like bathing, cooking and laundry. we are working in a hospital so i can't skip bathing, nor the food and sleep as well.

== Participant 13
yes, days seems shorter when its next to night shift. 

== Participant 14
yes of course it shortens, i'm married and i have a daughter, i can't simply return from night shift and sleep, i have to cook, do household works, make breakfast lunch for husband and daughter, its difficult to complete sleep.

== Participant 15
yes, because at night i'm working during day i'm sleeping, so it seems short.

== Participant 16
yes, i feel tired and i sleep for half of the day during night shift and its of 12 hour so anyways it shortens my life.

== Participant 17
in our hospital night shift is of 12 hours, so working for 12 hours a really big thing. there can be 3-4 patients under one sister, i will complete my work but by 2am i'll feel sleepy anyway because its night, no matter how much i slept during the day, its common to feel sleepy during night. but, i have patients responsibility, anytime anything can go wrong with my patient so i have to be cautious. because of prolonged sitting i have back pain all the time and constipation is very common for me to have during night shifts. my shift will be over by 8am and i'll reach my room by 9am, even if i'll manage my morning routine and breakfast in one hour and sleep by 10 am, i'll atleast sleep till 3-4pm, so where day went i can't see.

== Participant 18
because i have to sleep after night shift and also have to do daily routine works so the day ends very fast.

== Participant 19
the day after night shift seems to be passed so fast, because it goes in sleeping.

== Participant 20
yes, for sure. only by 9am i reach my room after night shift and then daily activities and taking rest takes the entire day. i sometimes have headache also that disturbs in sleep even more.