= Are you happy with your work ?

== participant 1
yes im happy with my work.

== Participant 2
yes, i'm happy with my work.

== Participant 3
yes, i'm happy and satisfied by my work.

== Participant 4
yes of course, By helping someone, I feel good from inside.

== Participant 5
yeah, but not fully because i wanted to pursue something else.

== Participant 6
yes, i'm happy and i always want to learn more.

== Participant 7
yes, i'm happy.

== Participant 8
yes, i'm happy.

== Participant 9
with my work i'm happy but this surrounding id what i'm not happy with.

== Participant 10
no, because we work a lot but no body knows that, everyone remembers the doctors only and the salary is also very unsatisfactory.

== Participant 11
yes i'm happy.

== Participant 12
yes, there little problem physically to me, but i'm happy with my work.

== Participant 13
yes i'm happy.

== Participant 14
yes, but there is little pressure in this work.

== Participant 15
yes, i'm happy.

== Participant 16
with my work and ability i'm happy.

== Participant 17
yes, i love my profession.

== Participant 18
yes

== Participant 19
yes, i'm happy.

== Participant 20
yes, i'm happy with my work.