= How does bight shift effects your relationships ?

== Participant 1
I am not able to give time, I am telling in clear language, I am not able to give time to anyone, neither to family nor to friends, Because when I am sleeping I am unable to talk, then I am cooking, doing my work, looking at the clock and then leaving for duty. But this is only the problem of those 3 days.

== Participant 2
As I live in hostel, so I only talk on the phone with everyone, during night shift for 3 days, I do not talk to anyone, it is a problem. but still when my mother knows i'm going to stay awake whole nights for next 2 days even she gets tens for me.

== Participant 3
not much

== Participant 4
We work far away from home, and we visit home once a year. Talks happen on the phone only after taking out time.

== Participant 5
i am not able to even talk in phone during night shift.

== Participant 6
no, not much i can manage.

== Participant 7
we can't manage we can only make time for phone calls. we stay very far from our home so we rarely visit.

== Participant 8
we can't communicate properly as we stay far away from home and family. we can only call and ask how are they doing that's all. we have to cook, bath, take rest and duty is there so we don't get time.

== Participant 9
About night shift I do not tell my mother much because she gets upset, even if I speak, I speak well and tell only about 1 night.

== Participant 10
during night shifts we can't communicate to anyone, during morning and evening shift we can only give time to all the relations.

== Participant 11
yes, little bit. even in phone its difficult to maintain because when i'm free they are busy and when i'm free they are not there to talk to me.

== Participant 12
no, i don't feel like it disturbs relations.

== Participant 13
 no, for me i don't have disturbance in relationships.

 == Participant 14
 by god's grace my husband and my in laws supports me so from that side its ok, but one very painful thing is that i can't participate in events or programs and because of this my daughter also have to miss everything because my husband also works.

 == Participant 15
 no, not much

 == Participant 16
 yes, but not that serious.

 == Participant 17
 during night shift for those 2 days i don't know what's going on in my family, because 12 hours night i'm working, day time i'm sleeping and after that again i'm preparing for duty only. so for 2 days either i'm sleeping or i'm on duty, and i can't do anything to solve it.

 == Participant 18
 no no, i manage to call them while cooking or eating during the day so there is no such problems.

 == Participant 19
 it does affect relations but its manageable.

 == Participant 20
 we stay far from home, we can catch up with family only by phone and that 3days of we can't manage doing that either, so there is little problem because of that.