= Does disturbed sleep affects your appetite ? If yes, how ?

== Participant 1
Too much, I am losing weight, the timing of food is not being maintained. Because there is duty from 8 in the evening to 8 in the morning, then I have to have dinner at 7 in the evening and after having dinner so early I am not able to sleep why I have to go to duty, I am awake then feel hungry at night If I am carrying tiffin too, then I am eating it even more at the wrong time. In the next morning of duty, going to the room, eating something and sleeping, then getting up in the evening after eating something and leaving for duty. Time is not manageable at all. Can't even eat 3 time meals properly.

== Participant 2
In the morning and evening shifts, I am able to eat 3 meals on time, just in the morning breakfast is a little disturbed but it is manageable if I come in the morning after drinking tea or coffee, but during the night shift in the morning I go to the room at 9 am and then after getting refreshed I cook breakfast or food and in that round it is 10-11 o'clock and sleep also goes away till that. After that, there is a problem in falling asleep, then if I fall asleep, I will wake up at 4-5 pm, then again cooking for dinner, after eating a little something, I have to leave again at 7 o'clock.

== Participant 3
There is no problem in appetite, hunger seems to be with time but there is no time to eat food.

== Participant 4
yes, in eating time there is huge disturbance because of changing shifts. specially during night shift in the morning I go to the room by 9 am and then after getting freshed up either I'll cook breakfast or go out to have something and i'll comeback and sleep by 10:30 or 11am so i'll skip lunch and directly have evening snacks again out for duty.

== Participant 5
yeah, during night shift eating time is really disturbed. if i'm getting up for eating in during the day, sleep just goes away and i can't sleep after that. so i have to complete my sleep because i have to stay awake whole night. 

== Participant 6
yes, little bit. we can't eat when we are hungry, it always either gets delayed or we have to eat advance to join a shift. but its manageable.

== Participant 7
because of rotating shift eating time is being disturbed but appetite is still ok.

== Participant 8
yes little bit, because we won't get time in every shift to eat on time, either it will be delayed or advanced.

== Participant 9
yes, in appetite and digestion there is problem. i can't digest food when i'm awake.

== Participant 10
yes, during night shifts we have to come for duty before 8pm, how can i have dinner by 7 -7:30 pm and stay awake for whole night. if i bring dinner then, i can only eat after 12am because before that patients may ask for some assistance, and when i am having late night dinner its not being digest and i am having acidity.

== Participant 11
yes, because i have to eat by 7pm during night shift and i feel hungry in midnights so i carry tiffin boxes and eat late night i get time. that makes me many times sick and i have vomiting and acidity issues in next mornings because of that.

== Participant 12
yes, there is disturbance in appetite and it makes my stomach upset. One more thing happens with me, this maybe because of weakness, I feel more inclined to eat sweets after night shift, which also can harm in long term.

== Participant 13
no, not that seriously. our eating time changes every day.

== Participant 14
yes, we can't eat on time, its always in a different time than when we are exactly hungry.

== Participant 15
not much.

== Participant 16
actually i feel hungry in time but because we can't eat on time, there is problem in appetite.

== Participant 17
actually appetite is being disturbed in such a way, like i can't eat when i'm hungry as the time of having my meal changes every 2nd day with my changing shift. today i have morning shift i'll return to room by 2:30pm and have lunch by 3:30 - 4pm but on next day if i have evening shift i'll have my lunch by 12:30pm because i have to reach here by 1pm and so on for the night shift, different time of meal.

== Participant 18
sometimes it affects my appetite, specially when i'm physically not well and i'm having night shifts then i loose my appetite.

== Participant 19
yes, appetite is disturbed because we can't eat on time, eating time is also getting disturbed so on the appetite.

== Participant 20
yes, the time i'm hungry i won't have time to eat and by the time i'll be free my hunger would disappear. during night shift i feel hungry obviously as its 12 hours but just like last day i got a Tuberculosis patient so i couldn't even drink water whole night, i have to avoid food even if i'm hungry for many reasons.