= How do you feel about night shift ?

== Participant 1
Night shift is also good but Because the night shift is of 12 hours, so the body gets a little weak, Daily routine gets messed up, There is an off day after the night shift but it goes for sleeping and it does not seem to be an off day.

== Participant 2
to be honest, i don't like night shift much, because I am a fresher so staying awake all night has not become a habit for me yet. There is also another reason that there are no consultants in the night, so I get scared a little.

== Participant 3
Night shift doesn't feel so bad, but before joining the job, I was very excited for night duty, but now when I have to do 2 night shifts every week, it doesn't feel that good.

== Participant 4
Night shift feels good, because there is a lot of time to work. But it doesn't feel good to wake up again and again in the night shift.

== Participant 5
night shift i don't like much and the 1st reason is because it's of 12 hrs, then sleep disturbance is there.

== Participant 6
ok it is, as its 12 hour, its a very long shift so its little difficult in staying awake when patients are stable and we don't have any work to do after 12am to 2am, after that we start doing morning care of patients.

== Participant 7
its ok, in winters its little tough otherwise its ok.

== Participant 8
night shift is ok but its of 12 hours and whole night we have to stay attentive. when patients condition worsens we can't even sit for a while we'll stand by the side of patient for whole night and that's tough.

== Participant 9
night shift seems boring to me, its of 12 hour and we can't take rest.

== Participant 10
feel good or bad but we have to do night shift because in hospital setting we have to work both day and night. but yes sometimes its very irritating to do night shift because its 12 hours.

== Participant 11
night shift is of 12hours so its little difficult.  as i have to have my dinner by 7pm and stay awake for entire night then i'll reach my room after shift by 9am next morning, its little tough.

== Participant 12
night shift is okay, it makes little problem because i have to have dinner earlier than other days and whole night we have to stay awake that's there. 

== Participant 13
i don't feel good because its of 12 hours. 

== Participant 14
night shift is of 12 hours, so there is problem in having food on time and also the work load is continuous, without taking rest for 12 hours.

== Participant 15
night shift is ok but just because its of 12 hour its little tough.

== Participant 16
it is ok, but there is little problem, if patient's condition gets worsen during night its very difficult because i'll be running here and there inside ICU to find supporting equipments for patient and 1000s of new advices i'll have to follow that makes me really tired.

== Participant 17
night is the worst shift among all shifts, because there are many problems such as, there won't be available consultant doctors, no seniors will be there to guide if there is any emergency, so its difficult.

== Participant 18
night shift is ok , but little boring. it is of 12 hours so i finish all work by mid night and then its boring to stay awake entire night.

== Participant 19
i don't like night shift.

== Participant 20
it is ok, but its tough on 2nd night.