= What are the major negative effects of night shifts ?

== Participant 1
weight loss is the major negative effect of doing night shift for me.

== Participant 2
The major effect is that I get so busy balancing myself with the rotating shifts that I don't even get time to read anything, when I was an intern, it used to bother me a lot and that I will never forget. It seems that sometimes no other work can be done with the job where you have rotating shifts, if you want to do higher studies then you can do it by quitting the job.

== Participant 3
yeah, the major effect is that it consumes our time so much.

== Participant 4
no, there is no such major disturbance. little bit disturbances in eating and sleeping is manageable as we have only 2 night shifts per week.

== Participant 5
major negative effect for me is irritation in my eyes, i have vision problem and sensitivity to light.

== Participant 6
nothing such serious negative effect.

== Participant 7
i become weak after my night shift and i have acidity issues, thats the major issue for me.

== Participant 8
that i have severe acidity during night shift.

== Participant 9
no major negative

== Participant 10
sleep is being disturbed, and i feel very weak and tired after night shift.

== Participant 11
only my problem in digestion i would say is major problem of night shift for me.

== Participant 12
j

== Participant 13
i don't have any problem with night shift which i can call major.

== Participant 14
my daughter is young now she have school, tuition and all so i am not able to give her that much time, that's the major effect in my life.

== Participant 15
no there is nothing like that.

== Participant 16
there are many small difficulties i would not call those major, coz its manageable.

== Participant 17
major negative effect i would say it includes all types of physical problems like bladder bowel disturbance, acidity and indigestion and also unhappy mood resulting from those physical disturbances. 

== Participant 18
there is nothing like major issue for me because of night shift, but when i'm not able to sleep in day time during night shift for any reason, my health condition is getting disturbed and i'm falling sick.

== Participant 19
night shift makes me very week, its just 2 days but that 48 hours can make me very week for next 2 days.

== Participant 20
major problem is that in all other shifts we are working for 6 hours after that the time is ours we can do whatever we want after our shift, but for night shift 12 hours we are already in hospital and then we don't have any choice but to sleep, we can't even take time and cook something good. even after the duty is over i feel like we are under control of something.