= Suggestion to the hospital management and family members.

== Participant 1
But yes,  from the side of hospital management, if I could get a little something in the 2nd night for refreshment, because I would not prefer to rest, but if I had tea or coffee, it would have helped to stay awake. The family members of the nurse who lives with the family, must understand that sleep is very important for the health of the person and the family should respect his work and dedication and that respect and love can be shown by giving that nurse an appropriate environment, for Example, if there is any family discussion they can avoid it during night shift. They should avoid asking for time when the nurse's night shift is going on. these small things can help a nurse a lot. 

== Participant 2
There should be tea, coffee and some mid night snacks for the night shift, it would have been better, and the staffing pattern should also be changed, if there were extra helping staff, then the night staff would have been able to take a short nap.

== Participant 3
some mid night snacks or strong coffee would help a lot. as in some Government sectors there is a nurses station in each ward and during night sisters can take rest while other sisters would assist patients interchangeably.

== Participant 4
Tea coffee is the best idea, we can take tea break in turn.

== Participant 5
hospital management should be serious about staff's health and comfort, they should atleast provide tea coffee or they should keep a canteen open here and staff should be more so that atleast everyone can take a break in turn. 

== Participant 6
staffing pattern should be increased if the hospital management will think about staffs health, because if there will extra helping staff, we can atleast take little break in turn. i don't want to sleep, that should be allowed but atleast someone to watch my patient for 15-20 minutes so that i can atleast head down on table and take a break and this also i want only when my patient is stable otherwise no need of even that break. in such situation if there will be tea or coffee just to help us staying awake and feel refresh, that would help a lot. we all just want staffs should have burden staffing pattern should be that flexible.

== Participant 7
after finishing all work if patient is stable then we should be allowed to take 30 minutes break, and its only possible is staff is sufficient. for 12 hours we can't work or sit in front of a patient continuously. if management will keep eyes on staffing pattern and could give some mid night snacks, it would help us a lot.

== Participant 8
there should be a break allowed for all staffs in turns, because its difficult to sit or work continuous for 12 hour. if we would get a mid night snacks that would also help a lot in terms of refreshment.

== Participant 9
staffing pattern should be made flexible that staffs should be able relax and work smoothly.

== Participant 10
actually when i have a stable patient who is sleeping peacefully and his vitals are stable then i will complete the paper works by 11:30pm and i'll have to simply sit till 3am, i will definitely feel sleepy in such case if there will be extra helping staffs just to sit in front of my patient for 20-30 minutes then i can take a break. and its only possible when there is more than sufficient staffs, or if i have a very critical patient who needs continuous supervision then also i'll complete my paper work by 11.30 pm and i'll have to stay awake and supervise my patient for entire night so, in this case there is no option of taking break but i have to stay awake and attentive. in this type of situation we should get something like coffee or tea which can help in staying awake.

== Participant 11
support from the hospital management would help in a way if they would provide little more than sufficient staff that, when patients are stable, sisters could take a nap break in turns while an extra staff would just keep eyes on that sister's patient, or if patients are so critical that one have to keep eyes on continuous on patient then management can avail us some refreshment like juice/cold drink during summer nights and coffee/tea during winter nights.

== Participant 12
actually there should be a nap break allowed in turns, that is important, if it doesn't hamper our work it may hamper one personally. in long term its unhealthy for anyone doing night shifts. emotional support from family and loved ones is really important and also we need to maintain a good diet. 

== Participant 13
hourly we have to check vitals so we can't take break for more than 30 minutes. but if there will be extra staff to supervise then there is chances of taking nap break of 30 minutes in turn when the supervising staff can keep eyes on patient. 

== Participant 14
staffing pattern should be flexible. according to department and condition of the patient staffing pattern should be maintained. there should not be shortage of staff. extra staff for supervision should be provided so that sisters can 30 minutes of break. continuous 12 hour working shift can't be done in ease. by 2 am morning it feels so tired maybe a hot coffee would help during winters.

== Participant 15
sufficient staffs could help and tea coffee maybe, to work comfortably.

== Participant 16
sufficient staff should be maintained that will help a lot.

== Participant 17
during night shift there should be 2 staff for one patient so that 1 can guide the patient for 6 hours and other can do it for next 6 hours and they both can rest in turn, or they should divide night shift into short hours of shifts like 3 shifts of 4 hours so that without any break sisters could work comfortably and go, or for staying awake they can provide tea coffee everyone has used during there student life for staying awake during nights for studying.

== Participant 18
there should be extra helping staffs to assist all ICU staffs during night shift.

== Participant 19
from hospital management i would only ask for some tea or coffee for ICU nurses to help them stay refreshed and awake. i hope one day the staffing pattern will be considered seriously in india as well.

== Participant 20
in our hospital there is no special facilities for night shifts but many other hospitals where my friends are working provides at least mid night snacks and tea coffee are always available at nursing station. so, from our hospital management also i would ask for at least the same or only tea coffee maybe enough to help us staying awake at night.