= Are you doing night shift by your choice ?

== Participant 1
No, it is necessary to do 2 night shifts per week in the hospital, so it has to be done. If I had a choice, I would not have done the night shift.

== Participant 2
no, i'm doing night shifts just because it is compulsory to do atleast 2 night shifts every week. If I had a choice, I would not have done the night shift.

== Participant 3
Yes, there is a rule too, that's why I am doing night shift every week, otherwise I would just do it sometimes not every week.

== Participant 4
Yes, yes, I am doing by my choice, we should have experience of all shifts, what to do in which shift and what is the problem in which shift, all the staff should be aware of this.

 == Participant 5
 no, here its a rule to do 2night shifts per week that's why. actually initially night shift is not the main problem, the rotating shift is the problem that changes every 2nd day. if they would ask me to do 8 nights for a month in one go i'll do and stay relaxed for next 2 weeks of that month.

 == Participant 6
 yes, i'm doing by my choice.

 == Participant 7
 yes, but if there was any other option then i would never do night shift.

 == Participant 8
 yes, but if there will be option to choose i would never choose night shift and i'm sure nobody would.

 == Participant 9
 no, i always try not to get night shift.

 == Participant 10
 yes, and also because its a rule. if there will be option of choosing shift not every week but sometimes i would choose.

 == Participant 11
 yes, if there will be option of choosing shift, then also i'll sometimes choose to do night shift but not every week.

 == Participant 12
 yes, its my choice. because i should also be aware of what are the situations in night shift to maintain a good grip in my work.

 == Participant 13
 yes, by my choice.

 == Participant 14
 no, its the rule here to do atleast 2 night shifts per week, that's why.

 == Participant 15
 yes, and also because its rule here but its never forcefully done

 == Participant 16
 no, its rule here to do 2 night shifts per week.

 == Participant 17
 no, its because its a rule here.

 == Participant 18
 yes, by my choice.

 == Participant 19
 no, its just because its rule here to do at least 2 night shift per week.

 == Participant 20
 yes, because compared to other hospitals we are privileged and only have to work for 2 days in night while other hospitals asking for atleast 4 nights per week.