= How does night shifts affect marriage life, what has been your experience ?

== Participant 1
For those who are married, there may be some sourness in the relationship due to not being able to give time to each other. If both do not know well about each other's profession, then those people will not be able to balance lifestyle and behavior.

== Participant 2
Married people will have a little more problem, they will have to see 2 families, and those who have children will have more problems because how do we expect children to understand our work, and if we give more priority to work than children then We are playing with the lives of our children. And anyway, in every family, every member has to do some work during the day, then at night there is such a time when the whole family gets to meet, sits together and talk or eat together.

== Participant 3
for married people there might be some issues.

== Participant 4
In married life, there will be distance from children due to duty. And there will also be some attachment and communication gap with wife and family if they live far away like us.

== Participant 5
I think married people will have more problems because children will say that they have to talk to their father, if they want to meet, then there will be trouble. There is not much problem in single life.

== Participant 6
no, i don't think night shift can affect married life, we have chose this profession and we have to be flexible and family members should also understand the time burdens. but if family is not understanding then there maybe issues.

== Participant 7
i don't have idea about married life.

== Participant 8
no idea.

== Participant 9
in married life i think there won't be problem, it will be good if someone will have a wife to look after his food, laundries and also would care for him. i think it will help, if i'll get good homely cooked food i can do night shift in ease, because we have extra tension of cooking and washing and all.

== Participant 10
in married life there will be more issues regarding family. now we can go back after work cook or buy food eat and can take rest for full 8 hours but many married sisters say that, after shift they have to prepare food for family and children, do laundry and many household works. we can feel their problems. it will be very tough for a mother or father to maintain the love, affection and responsibility for children and family with shift work.

== Participant 11
i don't have idea about it.

== Participant 12
married life will get more disturbance as compared to our single life.

== Participant 13
i don't have any idea about a married life.

== Participant 14
actually me and my husband works in same hospital so there is not that big issues, because atleast he can understand this hospitals situations. but many of my friends always complains who's husbands are not in medical area that, they never understands what its like to work whole night.

== Participant 15
i'm not married but i can say that there would be more problems for sure as they can't choose to sleep over other important work like we can.

== Participant 16
maybe it will be more difficult for them to manage.

== Participant 17
in married life there will be more problems in initial time i think, parents understands our situations but the spouse may not understand that well. from my side also i know what my mother and father's health condition is and what possible problems they can have so i can guide them on phone as well, but if there is baby in my life i can't predict what problems can arise so i'll have to available for them also. so, there will be many more problems i think.

== Participant 18
they must be having more problem than us, but in nursing profession we have to manage by balancing some how.

== Participant 19
to married life night shift will affect more, because we bachelors can return from duty and sleep peacefully, but married person would have to get involved in house hold responsibilities andd may be children.

== Participant 20
in marriage life there will be many more problems i think. now i'm thinking about sleeping or going out, while after marriage the going out option i may not even keep as an option because there will be kids, husband, in laws and i think responsibilities towards family will be more and the need for rest will also increase by the time, its going to be very tough i guess.