= How does night shift affect your mood?

== Participant 1
Yes, irritable mood definitely happens after night, if someone says something, sometimes I overreact or I start showing rude behavior, I have felt it.

== Participant 2
yes, little irritations some times i have felt.

== Participant 3
mood becomes irritable when night shift comes, i starts getting rude sometimes, maybe because of tiredest and incomplete sleep.

== Participant 4
no, not as such but sometimes when i'm trying to sleep and someone plays loud music, i get irritated. i get angry and restless.

== Participant 5
The mood gets dull when the night shift is going on, there is irritability.

== Participant 6
yeah little irritation i have during night shifts.

== Participant 7
no no, for me there is nothing like that.

== Participant 8
mood disturbance like irritation happens many times  i have faced.

== Participant 9
no no not much, its just a shift its manageable.

== Participant 10
when my sleep is not complete, i won't feel good in anything and i'll be irritated.

== Participant 11
no no, not seriously.

== Participant 12
little irritation happens sometimes, but mood swings gets worsen when we get our periods during night shifts.

== Participant 13
yeah, just that irritable mood for 2 days.

== Participant 14
i am able to stay calm only to see my daughter's happiness otherwise this much effort won't be worth it.

== Participant 15
i take it as just a shift, and i don't think much about it so it never hampered me.

== Participant 16
mood change happens because of tiredness due to lack of rest.  i become easily irritated for small reasons and anger issues are increasing.

== Participant 17
mood remains irritable when i know that i have to stay awake whole night even after sleeping for 7-8hours during the day and my body won't support me whole night to work.

== Participant 18
yes but sometimes not always.

== Participant 19
mood stays irritable during those 2 days because of sleeplessness.

== Participant 20
on first night i get prepared to face that 12 hours night duty but on second night shift i can't manage to make my mind, i get stressed by just thinking about it and have headache, just like today, i have 2nd night shift and i already have headache.