= Does poor staffing pattern increase the impact of night shifts ? what may be the better staffing pattern for night shifts ?

== Participant 1
No, I think night shift has nothing to do with staffing pattern, because even if I get 3 patients, I will stay awake and even if I get 1 patient, I will not be able to rest why can't sleep in the ward because there is a big risk. 

== Participant 2
Yes, in night shift we can not handle as many patients as morning, a sister can handle 3-4 patients in morning but not in night, because 10 pm medicine has to be given in night, mid night medicine also and 6am medicine too, then again in the morning every patient's sponge bath, mouth wash, grooming, bed tidying is to be done, there are so many extra work which is not to be done during the day including writing handover and making new critical chart. Therefore the staffing pattern should be different in the night shift.

== Participant 3
yes, as such if we can get more staffs for night shift and can allocate less patients per staff like 2:1, it will bw better. 

== Participant 4
yes, It will make a difference, if I get more patients that I kept working the whole night, could not even sit for 1 minute, then there would be effect in work and also in health. That's why there should not be staffing like so much burden. staffing pattern for ICU at night shift Should be 1:2 or 1:3, there are more patients and if the condition of one patient is bad in the night, then the work of other patients will not be able to work.

== Participant 5
yes of course, when a sister have 3 patients and unfortunately a new patient arrives and she got allocated for that, there will be a huge burden as we need to many initial things for new patient like checking vitals, history taking, physical examinations and all and again after RMO visits and gives advice, order and give 1st dose of all the medicines prescribed, making a new file and writing handover, sending blood sample for full ICU profile and having x-ray done. staffing pattern is must to be modified. best pattern will be staff patient ratio of 1:2 patients are with ventilator, syringe pump so it can't be handled, for neuro-surgery post-op patients it should be 1:1. 

== Participant 6
yes, because the patients' condition in ICU are very serious, according the patients' condition staffing pattern should be maintained. when patient is in ventilator or have frequent refilling syringe pump or hypoglycemic then its a serious matter and needs continuous supervision so only one patient should be allocated, or more else one stable patient can be allocated with the serious patient. staff patient ratio should not be more than 1:2.

== Participant 7
in ICUs there is always critical patients, so we can't handle more than 2 patients as they need continuos supervision. in case of neuro patients only one patient per staff should be allocated.

== Participant 8
yes, when there is staff shortage its very difficult to work at night in ICU. staff should be always sufficient and the allocation should be fixed for the patient with specific staff, we should not change the allocation of the patient to new staffs who don't know the patient's conditions from initial days. 1:3 or 1:2 can be the best pattern for allocation.

== Participant 9
yes, definitely. once there was one staff absent in our ward, and because of that we had to handle more patients. its tough to work continuos for 12 hr, we need little relaxation. one staff can not handle more than 3 patients in ICU.

== Participant 10
yes, poor staffing pattern worsens the night shifts. if staff patient ratio will be 1:2 then its good.

== Participant 11
yes, it increases work load for us. if patient is in ventilator or have syringe pump on then it should not be allocated more than 2. that will be the best pattern in ICU.

== Participant 12
yes, the work pressure increases when there is less staff. in ICU there should be maximum 2 patients allocated to 1 staff. if patients are stable then maybe 3 but not more than that.

== Participant 13
yes pressure increases if allocation increases. maximum should be 3 when patient's are stable, 2 patients when one is critical and one is stable, not more than that.

== Participant 14
yes, it increases the pressure. see now there its christmas season, many sisters are on leave there is little more pressure in work. it happens during festivals like during durga pooja we want to take leave but we can barely get leave for maximum 2-3 days because everyone wants to enjoy so they can't grant leave for everyone together. in neuro-surgery icu if craniotomy or cranioplasty post operative patient is there, sister can't handle more than one patient.

== Participant 15
yes, when there is staff shortage its difficult to work, for ICU staff patient ratio should be 1:2 - 1:3.

== Participant 16
yes, poor staffing pattern makes night shift worse. best should be 1:2 in ICU.

== Participant 17
yes it increases the pressure, if my capacity is of handling 2 patient and i'm getting 3-4 patients, its really difficult to manage. ideally there should be 1:1 allocation in ICU.

== Participant 18
yes, it worsens the situation when there is shortage of staff during night. i had experienced when there was staff shortage, i used to work with4 patients in ICU from which 2 patients were in in ventilation. in ICU there should be one critical patient given to one staff, there can be two more stable patient with that, but more than 1 patient should nit be critical.

== Participant 19
yes, the critical patients increases the work pressure, the best staffing pattern would be maximum 1:3 if patients are stable and minimum 1:1 when the patient is critical and needs continuos supervision.

== Participant 20
yes of course, its not only in night but also in morning shift staff shortage hampers a lot, yesterday i had morning shift and i was allocated for 5 patients, because now its christmas season and many staffs are on leave, one of my patient had medicine opinion so the physician came and was giving round and at the same time our surgeon came for rounds so i was really stressed about that and i had to call other colleagues to help me. staff should be available and ideally in ICU staff patient ratio should be 1:1 but its fine if its minimum 2 patients and maximum 3 patients per staff but not more than that.