= Do you think night shift can affect vigilance, If yes, how ?

== Participant 1
No, I have never had problems with being attentiveness or being careful. Not in 1st night and not in 2nd night.

== Participant 2
It happens a bit as if there is a mistake in writing in the critical chart or the paper gets exchanged of any patient with other patients. Happened to me earlier, 1 time, I had exchanged the papers of both my patients, by mistake I had placed the patient's paper on that patient's table.

== Participant 3
no, According to the situation in front, that alertness comes.

== Participant 4
no, i don't think night shift can affect vigilance. On the contrary, I become more attentive in the night because there is fear, there are no consultants in the night.

== Participant 5
yes, i had such experiences like i kept one patient's critical chart on the other patient's table. 

== Participant 6
no, i don't think.

== Participant 7
no, i don't think.

== Participant 8
no, night shift gives us tiredness but it can't affect vigilance.

== Participant 9
no, vigilance can't be disturbed because of night shift on first night but on second night i feel lethargic but there was disturbance in vigilance.

== Participant 10
no no, i don't think.

== Participant 11
no i don't think it can hamper in such way.

== Participant 12
yes, i have heard it has happened with some people.

== Participant 13
no, people are careful about this, when there is critical patient under me i will never feel sleepy because i'll be cautious about my patient.

== Participant 14
in earlier days it may affect if we are not careful enough, after some experience i don't think it can affect.

== Participant 15
maybe yes, but i never seen anyone having trouble in vigilance.

== Participant 16
yes it affects, because of our incomplete sleep we can't stay that attentive, there is chances of errors.

== Participant 17
yes, it can happen. if i'm not attentive enough because of tiredness and lack of sleep, i can miss some communication or order got from someone or i may not understand that clearly because of sleepiness.

== Participant 18
i don't think, if i am serious about my duty it won't happen.

== Participant 19
yes, it can affect the vigilance. if the sister is not well prepared to stay awake whole night there is chances of error in work maybe due to inability to pay required attention.

== Participant 20
yes, night shift can be very boring for some people as its a long 12 hours shift and if the person won't be careful enough there is chances of vigilance trouble.