= Which shift work you like the most and why ?

== Participant 1
i prefer  morning shift, because Due to waking up early in the morning, the body feels refreshed and Get time to rest after leaving duty. There is no problem in sleeping time, I get my personal time too.

== Participant 2
morning shift i like most, After the morning shift, we get the whole afternoon, if there is any work then we can do it, can plan something with friends, can cook something good. we can get our personal time that's why.

== Participant 3
evening, Because I do not have to get up in the morning, I get enough sleep, and even after duty I do not have to wake up in the night, I sleep comfortably.

== Participant 4
morning, because i Feel fresh in the morning to work, and gets time even after shift.

== Participant 5
evening shift, because i don't miss any of my meals during evening shift, in morning i have to miss breakfast and in night shift every meal will get disturbed and also our sleep.

== Participant 6
morning, because we can discuss about the patient and the care plan with the consultant, its only possible in morning shift as there will be doctors round only once a day and that will be in morning shift. i always want to know all the why and how we are providing which type of care to the patient, there shouldn't be any doubt.

== Participant 7
evening, because we can manage everything on time. we can get up easy in the morning cook, bath, eat and come for duty and can return by 8:30 pm. so, its comfortable.

== Participant 8
morning, because i can get little time for me after my shift.

== Participant 9
evening, because i don't have to face doctors and also that shift is flexible.

== Participant 10
evening, because in this shift we can do everything in a very organized way, nothing will get disturbed. i cane wake up easy in the morning, fresh up, cook and have breakfast and lunch on time then come for duty and return by 8:30pm and have dinner and good sleep.

== Participant 11
morning, i get full afternoon for me after that shift.

== Participant 12
evening, because as compared to other shifts this one is most comfortable. in morning shift i have to wake up early morning and in night shift i have to stay awake whole night.

== Participant 13
morning, because it's refreshing to work in the morning and i get time.

== Participant 14
evening, because we can take food properly on time during this shift.

== Participant 15
morning, because after the shift i get time.

== Participant 16
morning, except for getting up early morning, i get more time for me after the shift. so i like this shift.

== Participant 17
morning, because in morning shift the benefit in duty is that all senior staffs and doctors are available, the doctors round and doing pre-op for patients, medicines and all takes the whole shift so it ends very fast. then after shift i get my personal time too.

== Participant 18
morning, because i can give round with patient and know everything about patient's care plan.

== Participant 19
evening, because in morning i can cook and eat on time and come for duty easily and that's comfortable.

== Participant 20
morning, i like the most because there will be consultants available to guide us. 