= Are you facing any psychological or mental problems because of disturbed sleep, please share your experiences?

== Participant 1
No, no, I have never felt any psychological issues.

== Participant 2
no, i never had any psychological problem.

== Participant 3
no, i would not call it psychological issue but there is little irritation.

== Participant 4
no, we can't call it a psychological problem. sometimes when we have other disturbances in our personal life and we have night shifts there may be some mood swings.

== Participant 5
If we do clinical duty of psychological problems but by the end of 10 years, we will all have CKD.

== Participant 6
i never faced any psychological issues.

== Participant 7
no, i never had any experience.

== Participant 8
not psychological i can't say it psychological problem.

== Participant 9
no no, not because of night shift but if there will be any extra tension of home or friends then it affects like i won't feel stable.

== Participant 10
no, we can't call it psychological issue.

== Participant 11
no, because of duty there is nothing like psychological problem.

== Participant 12
no not as such.

== Participant 13
not that evident i would say, but there is change in mood and little irritable my mood becomes during night shift maybe because of discomfort i feel due to incomplete sleep.

== Participant 14
yes the pressure of work and helplessness for my family makes me exhausted some times i even feel depressed, but because of my husband's support i'm able to manage.

== Participant 15
 no, i never such issues i just set my mind to work smoothly.

== Participant 16
no, not as such.

== Participant 17
disturbed sleep won't let us keep calm, we may behave normal but from inside those 2 days it feels like i don't know this world.

== Participant 18
not as such, but sometimes due to construction in that area i am not able to sleep at all during the day and i have night shift then i get irritated and mood becomes very disturbed.

== Participant 19
no i never experienced any psychological issues in major, there is little mood swings especially on 2nd day of night shift.

== Participant 20
yes, sometimes its like i get irritated and feel like i'm just not happy because i can't have my own time as i wish.