= How does night shift affects your sleep patterns ?

== Participant 1
There are 2 night shifts in a week, so in the long term there is not much disturbance in the sleeping pattern. This is one benefit of this hospital i would say.

== Participant 2
Sleeping pattern is completely disturbed, because as today is day shift, so I will be able to sleep tonight but our shift changes frequently so no one specific sleeping pattern is maintained. One advantage of this is that we have to do every shift 2 times in a week, then we have to do only 2 nights, whereas in other hospitals we have to do full week nights.The sleeping pattern is disturbed not only because of the night but also because of the frequently changing shifts.

== Participant 3
sleeping pattern is being changed every 2nd day because of rotating shift.

== Participant 4
not much, its every 2nd day changing so we just have to be flexible.

== Participant 5
Night shift is of 12 hours isn't it that's why there is less time in the day anyway, have to leave 1 hour before for duty and even after leaving by handover it becomes 1 hour, that means only one hour is available in the day, cook and eat in it Take bath, everything has to be maintained, then sleep also has to be completed. There is no sleeping pattern, nothing happens.

== Participant 6
yes, there is little disturbance in sleeping pattern. sometimes i'm able to sleep sometimes not, and because of staying awake in the nights i have issue in my eyes that get worse sometimes and i start having headache as well.

== Participant 7
my sleep time is only disturbed during night shift, other than that its ok.

== Participant 8
yes, there is no fix sleeping pattern we can only sleeping by calculating time.

== Participant 9
no no not much, 

== Participant 10
during night shift also we feel sleepy between 12-2am. sleep time is not that disturbed in long term.

== Participant 11
not much in long term.

== Participant 12
sleep pattern remains ok but i have additional issues because i can't sleep during day.

== Participant 13
in the beginning when i joined this job, i was so troubled to manage sleep awake timing in every second day changing shifts. but now i got balanced with this changing shift and i manage sleeping pattern differently in every shift.

== Participant 14
its not only night shift affects our sleeping pattern, every shift equally affects sleeping pattern.

== Participant 15
i don't have fixed sleeping pattern, when i get time i take nap.

== Participant 16
sometimes i don't get sleep even after staying awake for whole night.

== Participant 17
sleep pattern is being changed every 2nd day with the changing shift.

== Participant 18
only for 2 days during i sleep during day, other than that i don't have any difficulty in my regular sleeping pattern.

== Participant 19
yes, there is disturbance but we have to maintain by completing our sleep after night shift by devoting time for rest.

== Participant 20
i didn't had any sleep awake time for me so i won't complaint about sleeping pattern getting disturbed coz i already sleep late at night.