= Do you think your circadian rhythm is getting distracted ?

== Participant 1
My circadian rhythm is no longer there, there was a time when I was a student, I used to fall asleep at 10-11 pm and also wake up at 6-6:30 am. Right now sleep time is getting delayed day by day, it has gone from 10 pm to 3 am now. Another thing is that I am getting phone addict, because I am looking at phone to stay awake at night and it is becoming a habit.

== Participant 2
 there is nothing like a circadian rhythm for me right now, Rather, we have to find time to complete our sleep just by looking at the clock.

== Participant 3
no no, not much affect because as a student also i was not sleeping on time. rather now i feel more forced to sleep on time to maintain my shift works.

== Participant 4
no, i sleep by 10:30 -11pm every night and get up by 5-5:30am next morning, the only disturbance in sleep timing is for those 2 days during night shifts. 

== Participant 5
circadian rhythm is not there anymore, because of frequently changing shifts. Today was my morning shift, I got up in the morning at 5:30 am, then the in-charge called and said that the staff in the evening shift is short, you come in the evening. I did not sleep after that, and now after evening, I will go back in the night, such is the disturbance of our sleep.

== Participant 6
no no, only during 2 nights it won't be maintained but in long term there is no disturbance in circadian rhythm.

== Participant 7
no, i didn't had any fix sleep awake cycle earlier as well.

== Participant 8
yes, its fully disturbed.

== Participant 9
in long term not much disturbance to disturb circadian rhythm.

== Participant 10
 yes, initially i didn't had any such fixed sleep awake time but still now its the worst. there is no sleep awake cycle, i only sleep by looking at the watch to maintain shift timing.

== Participant 11
no i didn't had such sleep awake fix time for sleeping so i don't have problems regarding that.

== Participant 12
 yes little bit sometimes, not always.

== Participant 13
yes, circadian rhythm can't be maintained for shift working people because our sleep time changes every 2nd day.

== Participant 14
yes fully disturbed it is, in nursing profession we can't have a specific sleep awake cycle.

== Participant 15
i didn't had fixed sleep awake time ever so there is no such problems for me.

== Participant 16
i didn't had any fix sleep awake time, so there is no such issues.

== Participant 17
 before joining this job i had a sleep awake cycle which now no more exists.

== Participant 18
actually i didn't had any fix time of sleep and awake so i don't feel much troubled in that.

== Participant 19
there was a time when i was student i had sleep awake timings, now after joining the job where my shifts changes frequently its very obvious to get disturbed circadian rhythm.

== Participant 20
circadian rhythm was maybe good when i was kid, staying home with parents, back then mom will ask to go to bed by 10pm and next morning we have to wake up by 7 for school and all, but that got disturbed very early when i was graduating and staying in hostel with friends staying awake till late nights. so, i won't blame night shifts for disturbing my circadian rhythm.