= Does sleep quality affect your performance ?

== Participant 1
no no, Night shift has no effect on my performance, that means personally I have problems but there is no disturbance in work so far.

== Participant 2
Doesn't affect anything in performance, but maybe if we don't come for duty after balancing our sleeping problems by being well prepared.

== Participant 3
no no, i don't think night shift can affect our performance,.

== Participant 4
no, i don't think.

== Participant 5
yes, at night some disturbance in our performance happens, like we can't perform as clear and actively as the day shifts.

== Participant 6
no, its just a shift just like other shifts. i don't think it can affect anyone's performance.

== Participant 7
no no

== Participant 8
no, it doesn't.

== Participant 9
no no, personally i don't feel so attentive on the 2nd night shift but my performance remains the same.

== Participant 10
no, it never affected my performance towards patient.

== Participant 11
no, for me it didn't affected ever in my performance but yes when we go for getting vitals of patients they get disturbed they are stable saying, when we are trying to sleep you are disturbing.

== Participant 12
no, i don't think.

== Participant 13
no, i don't think it can affect my performance.

== Participant 14
no, my performance remains same.

== Participant 15
for me, no

== Participant 16
yes, i don't feel fresh or and comfortable to work.

== Participant 17
i think it can affect, because if my body is struggling of course it will be evident in my work. 

== Participant 18
no no, there is nothing like that.

== Participant 19
not now, but in initial days its was difficult to work in night shift.

== Participant 20
yes, it do affect the performance, if i couldn't get good sleep during day because of any reason, it'll be very tough for me to be attentive in night shift because i have headache if i'm sleepless and with that my performance may not be that fine.