= Do night shifts have impact on menstrual cycle ?

== Participant 1
 n/a

== Participant 2
no, in menstrual cycle i never noticed as such disturbance.

== Participant 3
N/A

== Participant 4
N/A

== Participant 5
n/a

== Participant 6
yes, i have delayed periods and that was because of incomplete rest and sleep.

== Participant 7
n/a

== Participant 8
no, for me it didn't affected but for many of my friends.

== Participant 9
n/a

== Participant 10
n/a

== Participant 11
n/a

== Participant 12
menstrual cycle is getting affected for many, as i said some are getting irregular periods like dates of getting periods varies by 10-12 days, one of my friend sometimes gets twice a month.

== Participant 13
n/a

== Participant 14
yes, i got to know about my hormonal issues because of that only, i started having irregular and delayed periods after few months of joining this job and i met to gynecologist. i have to stay conscious about my fluid intake timings and also about my diet, i still have to go for follow ups.

== Participant 15
no not yet.

== Participant 16
yes, i face delayed periods mostly and i'm also consulting to gynecologist.

== Participant 17
n/a

== Participant 18
n/a

== Participant 19
no, i personally never experienced any disturbance in menstrual cycle.

== Participant 20
yes, i get periods delayed or advanced by a week sometimes, mostly it gets delayed and gynac says its because of lack of sleep.