= Are you having daytime sleepiness because of night shifts ? If yes, share your experience ?

== Participant 1
There is day time sleepiness after night shift, atleast for 2 days, sometimes plans have to be canceled because of that.And due to waking up 2 nights in a week, sleep is getting late day by day.

== Participant 2
No no, I can't sleep during the day even after coming back from the night, and because of this, I have more problems.

== Participant 3
sometimes just after night shifts.

== Participant 4
sometimes in case if i could not sleep after my night shift because of some other work, then there is daytime sleepiness for one day but not more than that.

== Participant 5
Only one off is available in the week, that too after the night, the whole week is not free, you can just plan anything on the night off, but if you do not sleep on that day, there will be burning in the eyes and sleep will be a lot. And because of that there will be daytime sleepiness.

== Participant 6
no no, i manage my time to complete sleep on the day after night shift and it can't affect my other shifts i always stay focused.

== Participant 7
yes if i don't have any rush in work i'll feel sleepy but if patient is critical then i'll be alert and i won't feel sleepy.

== Participant 8
no

== Participant 9
yes, very severe daytime sleepiness.

== Participant 10
yes, i feel very sleepy during the day just after night shifts.

== Participant 11
no, other than the next mornings of night shifts, i never had day time sleepiness.

== Participant 12
no, not daytime sleepiness but i have fatigue for next 2 days,  because i can't sleep during day.

== Participant 13
yes, sometimes if i couldn't complete my sleep on my night off, i feel little sleepy during the next day.

== Participant 14
yes, because i can't complete my sleep. when its the evening shift after night off i feel sleepy. in whole week we get one day off that is after night, my daughter expects from us to visit some places or go out for movie or to relatives house, we have to do that atleast for her, so we can't rest during the day. so obviously this will happen.

== Participant 15
no, i never faced.

== Participant 16
yes some times, if i couldn't sleep during the day after doing night shift, then next days i feel sleepy.

== Participant 17
no, except the just next morning when i return from night shift, i never had such experience.

== Participant 18
during initial days i had some problem but later on i got habituated and now i don't have day time sleepiness.

== Participant 19
yes, it depends on the tiredness we'll have during night shift. the more pressure during work the more day time sleepiness i experience.

== Participant 20
yes, day time sleepiness is my problem. like, once i went out with friends on my night off day and so during day i didn't took rest, at night i slept of course but the next whole day i was feeling dizziness and sleepy.