=	Do you think people are leaving job because of night shifts ?

== Participant 1
no no, It does not affect to such an extent that people leave the job and go away.

== Participant 2
Yes, not the profession but people change jobs, more and more married people look for a general shift job. Even if I get such an option, then I will definitely suck the job of general shift.

== Participant 3
maybe yes, if i would get a chance to get only day shifts i will definitively choose that.

== Participant 4
no, if i will only seek to get day shifts then its not good, everyone should experience every shifts and also take rest, its anyways not that hectic to leave the job.

== Participant 5
yes, many people left this hospital and joined to some small clinics to get a general shift 9 to 5 job. even if i'll get a chance i'll go for day shifts.

== Participant 6
no, i don't think. i also won't leave my job because of night shift.

== Participant 7
no, i don't think. even i won't leave job because of night shift.

== Participant 8
yes, people can leave.

== Participant 9
yes, of course.

== Participant 10
no, i don't think. if someone can't do night shift then they should not choose this profession. 

== Participant 11
no, i don't think. 

== Participant 12
yes, people can leave i think also i have seen people. but actually there should be option to choose also in india like in other countries, that would be good so people can choose and can work happily.

== Participant 13
no, i don't think.

== Particular 14
yes maybe people can leave job if they get other option like having a job with only day shifts.

== Participant 15
no i don't think.

== Participant 16
no, i don't think.

== Participant 17
yes, people can, even i will leave if i'll get better opportunity.

== Participant 18
i don't feel personally, but people can leave i think.

== Participant 19
yes, if people will get an opportunity to choose shift, people can leave the job to avoid night shift.

== Participant 20
i can't say about others leaving job but if i'll get a chance to avoid night shift and work only day shifts i'll definitely choose that. 