= Is there some benefit of doing night shift, if yes what are those benefits ?

== Participant 1
no, there is no benefit of doing night shift for me to be honest.

== Participant 2
no, i don't feel any benefit of doing night shift.

== Participant 3
no, i don't find any benefit of doing night shift. we are getting a night off after doing 2 night shifts but that's totally useless and it goes only for sleeping, there is difference in day off and night off and day off is useful.

== Participant 4
no, i don't think there is any benefit.

== Participant 5
no, there is no benefit of doing night shift.

== Participant 6
no such benefit is there, only thing is that we get more time and peaceful environment to work.

== Participant 7
i don't think there is any benefit of doing night shift. there is an off day we get after night shift but that is useless because it goes for sleeping.

== Participant 8
no, there is no such benefit of doing night shift but yes Night off helps when we take a long leave, if we take it after night off, then we get an extra leave.

== Participant 9
no, there is no benefit i can see for doing night shift, i feel bad only because of night shift otherwise i love our profession. Sometimes I think to find a job in some day care center so that I don't have to do night shift.

== Participant 10
no, there is no benefit.

== Participant 11
no, i don't find any benefit of doing night shift.

== Participant 12
yes, during night there are many things which we can't learn during day shifts, such as what investigations comes under an ICU profile, ABG is only done compulsorily in the early morning everyday that we won't get much chance to learn during the day shift. one most important thing is to build and maintain IPR is best made during night shift by giving sponge bath, hair care, bed tiding for the patient. that bonding can't exist only by giving medicine. 

== Participant 13
no, i don't think there is any benefit.

== Participant 14
there is no benefit of doing night shift is nothing here in india.

== Participant 15
yes, the whole day we get on the 1st day of night shift and also after the night shift we get an off day. in the day shifts we have to give rounds with doctors, dietitian also there will be visiting hours when patient's family comes to meet, there is many disturbances during day in our work but at night we can work peacefully.

== Participant 16
no, there is no benefit.

== Participant 17
no personally there is no benefit.

== Participant 18
no there is no benefit.

== Participant 19
there is no benefit of doing night shift. there are circumstances which makes night shift little better, like the weekly off we can only after night shift, so there is a hope that i will get a off after 2 days of night shift, and the day time we get which can be used for something emergency or important work we have to do because in no other shifts we'll get free time during the day.

== Participant 20
no, i don't see any benefit of doing night shift, morning and evening shifts are much better than night shift.