= How can we balance shift work and family ?

== Participant 1
I don't have to balance anything like that because I tell on the phone that I will not be able to talk for 2-3 days, I am sleeping, night shift, etc. And they people understand, I manage them like this.

== Participant 2
I don't live with family but I feel that if I was with family, means my mother was here, atleast would cook food for me for 3 times, and thus I would be able to complete my sleep and After waking up, there was no tension of cooking and my mother would also be with me.

== Participant 3
for me there is no such problem for family i manage by calling them time to time.

== Participant 4
There is nothing like managing in the family. I live so far away, just talk in video call when it is off day. I go home once in a year, I am able to give only that much time, I am not able to see even the smallest event of the house, even if someone becomes ill, I am only able to do suggest them where to go what to do or i send money.

== Participant 5
when there is an off day, we could manage to talk on phone. other days we can't talk, means those long talks are not possible.

== Participant 6
i am able manage by dividing time according to shifts for doing calls or visiting them.

== Participant 7
we can balance by making time like today after shift i'll call my mom.

== Participant 8
after work we can give little time, talking while cooking and all, like this only it can be managed.

== Participant 9
we have to manage by giving time after our shifts.

== Participant 10
we can inform on the day of 1st night shift about our duty, and we can talk to family after night shifts during morning and evening shifts. i do like this only.

== Participant 11
i maintain my family relations by calling them positively on my off days and other shifts like morning and evening.

== Participant 12
it varies individually, i manage time and call on other days.

== Participant 13
i will give time on the other half of the day, after or before my shift to my family that's all i can do. 

== Participant 14
i request our in-charge to adjust my roaster, many times i have done 4 nights continuous so that for next week i can be free during night just to participate in family functions.

== Participant 15
by dividing time, when to talk to family and when to manage the other stuffs, thats all we can do.

== Participant 16
just like that, by calling them when i get time like for in morning shifts i call them in evening

== Participant 17
by saying the truth, and giving as much as time i can give.

== Participant 18
by dividing the time we are getting after the shifts.

== Participant 19
we can't manage, there is no way to manage work and family life balance. we can only manage by choosing any one at a time, duty or family life.

== Participant 20
There is nothing like balancing, actually here its either or situation. for my family life i don't have much trouble because they understand so we talk before and after night shifts but for social or even my personal interest to go out visit places are not possible because the only weekly off i get is after night shifts so either i can sleep and take rest or after working for 12 hours night shift go out and enjoy. its tough both ways.